[package]
name = "peroxide"
version = "0.2.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dirs = "6.0"
anyhow = "1.0"
ssh2 = "0.9.5"
tokio = { version = "1.43.0", features = ["full"] }